=begin
#Topological Inventory Ingest API

#Topological Inventory Ingest API

OpenAPI spec version: 0.0.1
Contact: agrare@redhat.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for TopologicalInventory::IngressApi::Client::AdminsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AdminsApi' do
  before do
    # run before each test
    @instance = TopologicalInventory::IngressApi::Client::AdminsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AdminsApi' do
    it 'should create an instance of AdminsApi' do
      expect(@instance).to be_instance_of(TopologicalInventory::IngressApi::Client::AdminsApi)
    end
  end

  # unit tests for save_inventory
  # save inventory
  # Submits a payload to be persisted to the database
  # @param [Hash] opts the optional parameters
  # @option opts [Inventory] :inventory Inventory payload
  # @return [nil]
  describe 'save_inventory test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
