=begin
#Topological Inventory Ingress API

#Topological Inventory Ingress API

OpenAPI spec version: 0.0.2
Contact: agrare@redhat.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for TopologicalInventory::IngressApi::Client::DefaultApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @instance = TopologicalInventory::IngressApi::Client::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@instance).to be_instance_of(TopologicalInventory::IngressApi::Client::DefaultApi)
    end
  end

  # unit tests for save_inventory
  # save inventory
  # Submits a payload to be persisted to the database
  # @param [Hash] opts the optional parameters
  # @option opts [Inventory] :inventory Inventory payload
  # @return [nil]
  describe 'save_inventory test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for search_schemas
  # searches schemas
  # By passing in the appropriate options, you can search for available inventory schemas in the system 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :search_string pass an optional search string for looking up schemas
  # @option opts [Integer] :skip number of records to skip for pagination
  # @option opts [Integer] :limit maximum number of records to return
  # @return [Array<Schema>]
  describe 'search_schemas test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
