=begin
#Topological Inventory Ingress API

#Topological Inventory Ingress API

OpenAPI spec version: 0.0.2
Contact: agrare@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TopologicalInventoryIngressApiClient::InventoryObject
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InventoryObject' do
  before do
    # run before each test
    @instance = TopologicalInventoryIngressApiClient::InventoryObject.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InventoryObject' do
    it 'should create an instance of InventoryObject' do
      expect(@instance).to be_instance_of(TopologicalInventoryIngressApiClient::InventoryObject)
    end
  end
end
