=begin
#Topological Inventory Ingest API

#Topological Inventory Ingest API

OpenAPI spec version: 0.0.1
Contact: agrare@redhat.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TopologicalInventory::IngressApi::Client::InventoryObject
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InventoryObject' do
  before do
    # run before each test
    @instance = TopologicalInventory::IngressApi::Client::InventoryObject.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InventoryObject' do
    it 'should create an instance of InventoryObject' do
      expect(@instance).to be_instance_of(TopologicalInventory::IngressApi::Client::InventoryObject)
    end
  end
end

